image: docker:latest
services:
    - docker:dind
stages:
    - deploy
before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker version
    - docker-compose version
build:
    stage: deploy
    script:
        - ls -la
        - mv .env.gitlab .env
    tags:
        - docker
