image: runner:compose
variables:
    DOCKER_DRIVER: overlay
#services:
#    - docker:dind
stages:
    - tests
    - deploy
before_script:
    # Software
    - docker version
    - docker-compose version
    # Configure ssh
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Configure docker-compose
    - mv .env.gitlab .env
    # Up
    - docker-compose build
    - docker-compose up -d
    - docker-compose ps
    # Run
    - ./docker-exec composer --working-dir=framework install
migrate:
    stage: tests
    environment: tests
    script:
        - ./docker-exec framework/yii migrate/up
        - ./docker-exec framework/yii access/install
    tags:
        - compose
dev:
    stage: deploy
    environment: dev
    script:
        - sshpass -p $SSH_PASSWORD rsync -riz --links --delete -e "ssh" --exclude-from="exclude.txt" . $SSH_USERNAME@$SSH_HOST:$SSH_DIRECTORY
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-mysql-backup -c cmf2devvpsru_mysql_1"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-cron /root/cron/tabs"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-exec framework/yii migrate/up"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-exec framework/yii access/install"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-exec framework/yii cache/flush-all"
    only:
        - master
    tags:
        - compose
production:
    stage: deploy
    environment: production
    script:
        - sshpass -p $SSH_PASSWORD_PROD rsync -riz --links --delete -e "ssh" --exclude-from="exclude.txt" . $SSH_USERNAME_PROD@$SSH_HOST_PROD:$SSH_DIRECTORY_PROD
        - sshpass -p $SSH_PASSWORD_PROD ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd $SSH_DIRECTORY_PROD && /usr/local/php71/bin/php framework/yii migrate/up"
        - sshpass -p $SSH_PASSWORD_PROD ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd $SSH_DIRECTORY_PROD && /usr/local/php71/bin/php framework/yii access/install"
        - sshpass -p $SSH_PASSWORD_PROD ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd $SSH_DIRECTORY_PROD && /usr/local/php71/bin/php framework/yii cache/flush-all"
    only:
        - production
    tags:
        - compose
after_script:
    # Down
    - docker-compose down
    # Cleanse
    - find . -delete
