image: runner:compose
stages:
    - tests
    - deploy
before_script:
    # Software
    - docker version
    - docker-compose version
    # Configure ssh
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Configure docker-compose
    - cp .env.gitlab .env
    # Up
    - make docker/build
    - make docker/up
    - make docker/ps
tests:
    stage: tests
    environment: tests
    script:
        # Configure application
        - cp html/.env.gitlab html/.env.local

        - make install
    tags:
        - compose
    only:
        - schedules
develop:
    stage: deploy
    environment: develop
    script:
        # Composer self install
        - composer global require yii2-developer/recipes ~0.0.2

        # Deploy
        - sshpass -p $SSH_PASSWORD dep deploy:multiplex
        - sshpass -p $SSH_PASSWORD dep deploy:environment
        # - sshpass -p $SSH_PASSWORD dep deploy:develop
    variables:
        SSH_DIRECTORY: "$SSH_DIRECTORY"
        SSH_HOST: "$SSH_HOST"
        SSH_PORT: "$SSH_PORT"
        SSH_USERNAME: "$SSH_USERNAME"
    only:
        - master
    tags:
        - compose
    except:
        - schedules
production:
    stage: deploy
    environment: production
    script:
        - echo 'TODO'
    only:
        - production
    tags:
        - compose
    except:
        - schedules
after_script:
    # Down
    - make docker/down
    # Cleanse
    - find . -delete
