image: docker:latest
variables:
    DOCKER_DRIVER: overlay
services:
    - docker:dind
stages:
    - deploy
before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker version
    - docker-compose version
build:
    stage: deploy
    script:
        - $CI_PROJECT_DIR
        - $CI_PROJECT_PATH
        - mv .env.gitlab .env
        - docker-compose up -d
        - docker-compose ps
        - ./docker-exec ls -la
    tags:
        - docker
after_script:
    - docker-compose down
    - rm -rf /builds/$CI_PROJECT_DIR
