stages:
    - test
    - deploy
before_script:
    - docker info
    - docker version
    - docker-compose version
migrate:
    stage: test
    script:
        - mv .env.test .env
        - docker-compose up -d
        - ./docker-exec composer --working-dir=framework install
        - ./docker-exec framework/yii migrate
        - ./docker-exec framework/yii access/install
        - docker-compose down
    only:
        - master
    tags:
        - shell
dev:
    stage: deploy
    environment: dev
    script:
        - sshpass -p $SSH_PASSWORD rsync -riz --links --delete -e "ssh" --exclude-from="exclude.txt" . $SSH_USERNAME@$SSH_HOST:$SSH_DIRECTORY
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-mysql-backup -c cmf2devvpsru_mysql_1"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-cron /root/cron/tabs"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-exec framework/yii migrate/up"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-exec framework/yii access/install"
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST "cd $SSH_DIRECTORY && ./docker-exec framework/yii cache/flush-all"
    only:
        - master
    tags:
        - shell
production:
    stage: deploy
    environment: production
    script:
        - ls -l html
    only:
        - production
    tags:
        - shell
