image: docker:latest
variables:
    DOCKER_DRIVER: overlay
services:
    - docker:dind
stages:
    - deploy
before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker version
    - docker-compose version
deploy:
    stage: deploy
    script:
        - mv .env.gitlab .env
        - docker-compose up -d
        - docker-compose ps
        - ./docker-exec composer --working-dir=html/framework/yii migrate/up
        - ./docker-exec composer --working-dir=html/framework/yii access/install
    tags:
        - docker
after_script:
    - docker-compose down
    - find . -delete
