version: '3'
services:
    application:
        image: ${IMAGE_APP_NAME}
        container_name: ${CONTAINER_NAME}
        environment:
            APACHE_RUN_ID: ${APACHE_RUN_ID}
            APACHE_RUN_USER: ${APACHE_RUN_USER}
            APACHE_RUN_GROUP: ${APACHE_RUN_GROUP}
            CRON_FILE: /var/spool/cron/config/crontab
        volumes:
            - ./html:/var/www/html
            - ./docker/.composer:/var/www/.composer
            - ./docker/container/var/log/apache2:/var/log/apache2
            - ./docker/container/var/log/supervisor:/var/log/supervisor
            - ./docker/container/var/spool/cron/config:/var/spool/cron/config
            - ./docker/container/usr/log/supervisor:/usr/log/supervisor
            - ./docker/container/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/container/etc/supervisor/application.conf:/etc/supervisor/application.conf
        expose:
            - 9000
        depends_on:
            - redis
            - mysql
        networks:
            self:
                ipv4_address: ${NETWORK_APP}
    redis:
        image: redis:3.2
        container_name: ${CONTAINER_NAME}-redis
        networks:
            self:
                ipv4_address: ${NETWORK_REDIS}
    mysql:
        image: mysql:5.7
        container_name: ${CONTAINER_NAME}-mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./docker/container/var/lib/mysql:/var/lib/mysql
            - ./docker/container/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            self:
                ipv4_address: ${NETWORK_MYSQL}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${CONTAINER_NAME}-phpmyadmin
        links:
            - mysql:mysql
        environment:
            PMA_HOST: mysql
        volumes:
            - ./docker/container/etc/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
            - mysql
        networks:
            self:
                ipv4_address: ${NETWORK_PHPMYADMIN}
networks:
    self:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
