version: '2'
services:
  nginx:
    image: nginx:1.11
    volumes:
      - ./html:/var/www/html
      - ./docker/server/log:/var/www/log
      - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - php
    networks:
      self:
        ipv4_address: 172.72.7.2
  php:
    image: nsign/php-cmf2:latest
    user: 1000:1000
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./html:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    container_name: cmf2
    networks:
      self:
        ipv4_address: 172.72.7.3
    expose:
      - 9000
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: cmf2
      MYSQL_PASSWORD: cmf2
      MYSQL_DATABASE: cmf2
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/server/mysql:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      self:
        ipv4_address: 172.72.7.4
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
    volumes:
      - ./docker/config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      self:
        ipv4_address: 172.72.7.5
  redis:
    image: redis:3.2
    networks:
      self:
        ipv4_address: 172.72.7.6
networks:
  self:
    driver: bridge
    ipam:
      config:
      - subnet: 172.72.7.0/24
